from yoyo import step

steps = [
  step("CREATE TABLE MASTER_STOCK_LIST(" \
    "ISIN VARCHAR(20) PRIMARY KEY," \
    "BSE_SECURITY_CODE VARCHAR(15)," \
    "BSE_ISSUER_NAME  VARCHAR(2000)," \
    "BSE_SECURITY_ID VARCHAR(32)," \
    "BSE_SECURITY_NAME VARCHAR(2000)," \
    "BSE_GROUP VARCHAR(16)," \
    "BSE_FACE_VALUE FLOAT(2)," \
    "BSE_INDUSTRY  VARCHAR(2000)," \
    "BSE_SEGMENT VARCHAR(128)," \
    "BSE_NSURL VARCHAR(512)," \
    "LISTED_ON_BSE BOOLEAN ," \
    "NSE_SYMBOL VARCHAR(128)," \
    "NSE_NAME_OF_COMPANY VARCHAR(2000)," \
    "NSE_SERIES VARCHAR(4)," \
    "NSE_DATE_OF_LISTING DATE," \
    "NSE_PAID_UP_VALUE FLOAT(2)," \
    "NSE_MARKET_LOT INTEGER," \
    "NSE_FACE_VALUE FLOAT(2)," \
    "LISTED_ON_NSE BOOLEAN)"
)
]